version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        container_name: kernolab-api-redis

    mysql:
        image: 'mysql:8.0'
        container_name: kernolab-api-mysql
        working_dir: /application
        volumes:
            - '.:/application'
            - 'kernolab-mysql-volume:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=kernolab
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '8012:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: kernolab-api-webserver
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8010:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: kernolab-api-php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/xdebug.ini:/etc/php/8.1/mods-available/xdebug.ini'

volumes:
    kernolab-mysql-volume:
